name: sportfishing-env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4=4.9.3
  - ipykernel
  - jupyter=1.0.0
  - matplotlib=3.1
  - mysql-connector-c=6.1.11
  - mysql-connector-python=8.0
  - numpy=1.18.1
  - pandas=0.25
  - phantomjs=2.1.1=1
  - python=3.7
  - requests=2.23.0
  - scikit-learn=0.22
  - selenium=3.141
